### ISSUE TITLE
main layout

### ISSUE THREAD

**Issue by dcversus** [uz0/diary#2]

**Comment by dcversus** [comment]
![image](https://cloud.githubusercontent.com/assets/8696354/22923967/71aa2110-f2b4-11e6-882f-594c5a318a57.png)
Use angular material 2

**Comment by dcversus** [comment]
![image](https://cloud.githubusercontent.com/assets/8696354/22926220/c2f1e28a-f2bc-11e6-86c5-f1894abab8de.png)

**Comment by dcversus** [comment]
colors:
accent #f9690e
base #444

**Comment by danilstoyanov** [comment]
https://github.com/uz0/diary/commit/33db95062af9fad7adc67d5a5fe524edf004f628
***
